# Generated by Django 4.0.3 on 2022-04-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=200, verbose_name='Отчество')),
                ('passport_id', models.CharField(max_length=200, verbose_name='ID паспорта')),
                ('validity', models.DateTimeField(verbose_name='Срок действия паспорта')),
                ('who_gave', models.CharField(max_length=200, verbose_name='Орган выдачи')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_got', models.CharField(max_length=200, verbose_name='Кто получил')),
                ('summa', models.FloatField(verbose_name='Сколько')),
                ('reason', models.TextField(max_length=500, null=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер(id) товара')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование товара')),
                ('price', models.IntegerField(verbose_name='Закупочная цена товара')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_period', models.IntegerField(verbose_name='Срок рассрочки в месяцах')),
                ('first_payment', models.FloatField(verbose_name='Первый взнос')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null=True, verbose_name='Цена продажи')),
                ('rest', models.PositiveIntegerField(null=True, verbose_name='Остаток выплаты по рассрочке')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bereket.client', verbose_name='ID клиента')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bereket.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продажа и рассрочка',
                'verbose_name_plural': 'Продажи и рассрочки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bereket.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bereket.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Наличные',
                'verbose_name_plural': 'Наличные',
            },
        ),
    ]
